# ansible-deploy.yml

# Tâches de déploiement pour le projet ADSMA

- name: ADSMA
  hosts: all
  become: true
  become_method: sudo  # Utilise sudo pour l'élévation des privilèges
  become_user: root     # Spécifie éventuellement l'utilisateur à devenir
  tasks:
    # Affichage du Titre du Script
    - name: Print ASCII art
      debug:
        msg: |
          | [+] ADSMA Created by Romain.T, Dominique.G and Samuel.M [+]

    # Installation des paquets système requis
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg 
          - lsb-release
        state: latest
        update_cache: true
      changed_when: true
      register: system_packages_result

    # Affiche un message de succès si des paquets système ont été installés
    - debug:
        msg: "System packages installed successfully."
      when: system_packages_result.changed

    # Installation de python3-pip
    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present
        
    # Ajout de la clé GPG Docker au gestionnaire de paquets apt
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Ajout du dépôt Docker aux sources apt
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    # Mise à jour d'apt et installation de docker-ce
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    # Installation du module Docker pour Python via pip
    - name: Install Docker Module for Python
      pip:
        name: docker
    
    # A modifier on va récupérer le contenue depuis notre git https://github.com/W4RSH3LL/ASDMA.git - DG 
    # Git clone du projet Angular des Devops (specific branch)
    - name: Clone Docker Compose configuration from GitHub (specific branch)
      git:
        repo: https://github.com/EPSI-Leo/angular_project.git
        dest: /opt/angular_project
        version: DevOps
      register: git_output

    # Installation de docker-compose
    - name: Install docker-compose
      pip:
        name: docker-compose

    # Install Docker SDK for Python
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
          - "docker-compose"

    # Update Docker
    - name: Update Docker
      command: apt-get install docker-ce docker-ce-cli containerd.io --yes

    # Démarrage du docker-compose
    - name: Launch Docker Compose
      docker_compose:
        project_src: /opt/angular_project  # Specify the correct filename here
        state: present
