name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Updating Repositories
      run: sudo apt-get update && sudo apt-get upgrade -y
      
    - name: Installing dependencies
      run: sudo apt-get install -y git python3-pip

    - name: Installing requirements.txt
      run: pip install -r requirements.txt
      working-directory: ASDMA

    - name: Deploying ansible-playbook
      run: ansible-playbook deploy-ansible.yml -i inventory.ini
      working-directory: ASDMA/ansible
