name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Updating Repositories
      run: sudo apt-get update && sudo apt-get upgrade -y
      
    - name: Installing dependencies
      run: sudo apt-get install -y git python3-pip

    - name: Changing directory to /opt
      run: cd /opt

    - name: Cloning Repo
      run: git clone https://github.com/W4RSH3LL/ASDMA.git

    - name: Changing directory to /ASDMA
      run: cd ASDMA

    - name: Installing requirements.txt
      run: pip install -r requirements.txt

    - name: Changing directory to /ansible
      run: cd ansible && pwd && ls

    - name: Debugging
      run: cd ../.. && pwd && ls

    - name: Deploying are ansible-playbook
      run: ansible-playbook deploy-ansible.yml -i inventory.ini
    
    - name: Run tests
      run: echo "Running Tests"
